### ISSUE TITLE
Check de Duplicados na Coleciona-SUS

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/DCDup#10]
Quando fui fazer o check de duplicado da Coleciona-SUS aconteceu o seguinte problema

COMANDO
/home/javaapps/sbt-projects/DCDup/sh/DoubleCheckDuplicated.sh /bases/fiadmin2/DeDup/wrk/coleciona-sus/in_coleciona-sus_Sas.txt iso-8859-1 http://dedup.bireme.org/services lilacs_Sas LILACS_Sas_Seven /bases/fiadmin2/DeDup/wrk/coleciona-sus/out1_coleciona-sus_Sas.txt /bases/fiadmin2/DeDup/wrk/coleciona-sus/out2_coleciona-sus_Sas.txt /bases/fiadmin2/DeDup/wrk/coleciona-sus/out_ok_coleciona-sus_Sas.txt iso-8859-1

INICIO DO PROBLEMA

Remote check
<<< 0
<<< 250
<<< 500
<<< 750
<<< 1000
<<< 1250
<<< 1500
<<< 1750
<<< 2000
<<< 2250
<<< 2500
<<< 2750
<<< 3000
<<< 3250
Url=http://dedup.bireme.org/services/raw/duplicates/lilacs_Sas/LILACS_Sas_Seven
PostingString=[
LILACS_Sas|21533|An adapted ELISA method for differentiating pathogenic from nonpathogenic aPL by a beta 2 glycoprotein I dependency anticardiolipin assay|Thromb. res|2004|114|5-6|Levy, Roger Abramino//@//Meis, Ernesto de//@//Pierangeli, Silvia|573
LILACS_Sas|21534|Acculturation and Socioeconomic Position as Predictors of Coronary Calcification in a Multiethnic Sample|Circulation|2005|112|11|Roux, Ana V. Diez//@//Detrano, Robert//@//Jackson, Sharon//@//Jacobs Junior, David R//@//Schreiner, Pamela J//@//Szklo, Moyses|1557
LILACS_Sas|21535|A novel effect for annexin 1-derived peptide ac2-26: reduction of allergic inflammation in the rat|J. pharmacol. exp. ther|2005|313|3|Bandeira-Melo, Christianne//@//Bonavita, André Gustavo C//@//Diaz, Bruno L//@//Silva, Patrícia M R e//@//Carvalho, Vinícius F//@//Jose, Peter J//@//Flower, Roderick J//@//Perretti, Mauro//@//Martins, Marco A|1416
LILACS_Sas|21536|A new species of Wiedomys (Rodentia: Sigmodontinae) from Brazilian Cerrado|Mamm. biol|2005|70|1|Gonçalves, P R//@//Almeida, Francisca C//@//Bonvicino, Cibele R|46

MENSAGEM DE ERRO:

LILACS_Sas|22997|Apoptosis: target of cancer therapy|Clin. cancer res|2002|8||Ferreira, Carlos G//@//Epping, Mirjam//@//Frank A. E. Kruyt//@//Giaccone, Giuseppe|2024]
Response=[ERROR:]
[error] java.io.IOException: ERROR:
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated.rcheck(WebDoubleCheckDuplicated.scala:263)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated.$anonfun$remoteCheck$1(WebDoubleCheckDuplicated.scala:214)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated.$anonfun$remoteCheck$1$adapted(WebDoubleCheckDuplicated.scala:212)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:929)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error]         at org.bireme.dcdup.LineBatchIterator.foreach(LineBatchIterator.scala:24)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated.remoteCheck(WebDoubleCheckDuplicated.scala:212)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated.doubleCheck(WebDoubleCheckDuplicated.scala:108)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated$.delayedEndpoint$org$bireme$dcdup$WebDoubleCheckDuplicated$1(WebDoubleCheckDuplicated.scala:67)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated$delayedInit$body.apply(WebDoubleCheckDuplicated.scala:46)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at scala.App.main(App.scala:76)
[error]         at scala.App.main$(App.scala:74)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated$.main(WebDoubleCheckDuplicated.scala:46)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated.main(WebDoubleCheckDuplicated.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.Run.invokeMain(Run.scala:93)
[error]         at sbt.Run.run0(Run.scala:87)
[error]         at sbt.Run.execute$1(Run.scala:65)
[error]         at sbt.Run.$anonfun$run$3(Run.scala:69)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.util.Try$.apply(Try.scala:209)
[error]         at sbt.Run.directExecute$1(Run.scala:69)
[error]         at sbt.Run.run(Run.scala:78)
[error]         at sbt.Defaults$.$anonfun$bgRunMainTask$6(Defaults.scala:1146)
[error]         at sbt.Defaults$.$anonfun$bgRunMainTask$6$adapted(Defaults.scala:1141)
[error]         at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.util.Try$.apply(Try.scala:209)
[error]         at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:745)
[error] (Compile / runMain) java.io.IOException: ERROR:
[error] Total time: 712 s, completed Apr 5, 2018 4:34:43 PM
/bases/fiadmin2/DeDup/scripts

Grata

**Comment by heitorbarbieri** [comment]
Corrigido no commit 7b0563a
