### ISSUE TITLE
Check de Dedup do SciELO

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/DCDup#11]
Problema no check de Duplicado do SciELO

Comando:
/home/javaapps/sbt-projects/DCDup/sh/DoubleCheckDuplicated.sh /bases/fiadmin2/DeDup/wrk/sci_20180424/in_sci_20180424_Sas.txt iso-8859-1 http://dedup.bireme.org/services lilacs_Sas LILACS_Sas_Seven /bases/fiadmin2/DeDup/wrk/sci_20180424/out1_sci_20180424_Sas.txt /bases/fiadmin2/DeDup/wrk/sci_20180424/out2_sci_20180424_Sas.txt /bases/fiadmin2/DeDup/wrk/sci_20180424/out_ok_sci_20180424_Sas.txt iso-8859-1

Problema:
Remote check
<<< 0
<<< 250
Url=http://dedup.bireme.org/services/raw/duplicates/lilacs_Sas/LILACS_Sas_Seven
PostingString=[
LILACS_Sas|94|Material particulado dentro del macrófago alveolar|Acta toxicol. argent|2017|25|1|Falcon-Rodriguez, Carlos Ivan//@//García-Alonso, Larisa Idania//@//Segura-Medina, Patricia|23
LILACS_Sas|95|Modos del sufrimiento contemporáneo: Del síntoma al estrago|Anu. investig. - Fac. Psicol., Univ. B. Aires|2014|21|2|Arca, Gabriela//@//Mazzoni, M. Yanina//@//Naparstek, Fabián A.|17

Mensagem de ERRO:
LILACS_Sas|222|Trisomía 18 en mosaico: Serie de casos|Arch. argent. pediatr|2017|115|3|Cammarata-Scalisi, Francisco//@//Lacruz-Rengel, María A//@//Araque, Dianora//@//Da Silva, Gloria//@//Avendaño, Andrea//@//Callea, Michele//@//Stock, Frances//@//Guerrero, Yudith//@//Aguilar, Eliomar//@//Lacruz, María J//@//Sulbaran, Jesús|183-186
LILACS_Sas|222|Mosaic trisomy 18: Series of cases|Arch. argent. pediatr|2017|115|3|Cammarata-Scalisi, Francisco//@//Lacruz-Rengel, María A//@//Araque, Dianora//@//Da Silva, Gloria//@//Avendaño, Andrea//@//Callea, Michele//@//Stock, Frances//@//Guerrero, Yudith//@//Aguilar, Eliomar//@//Lacruz, María J//@//Sulbaran, Jesús|183-186]
Response=[ERROR:]
[error] java.io.IOException: ERROR:
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated.rcheck(WebDoubleCheckDuplicated.scala:263)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated.$anonfun$remoteCheck$1(WebDoubleCheckDuplicated.scala:214)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated.$anonfun$remoteCheck$1$adapted(WebDoubleCheckDuplicated.scala:212)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:929)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error]         at org.bireme.dcdup.LineBatchIterator.foreach(LineBatchIterator.scala:24)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated.remoteCheck(WebDoubleCheckDuplicated.scala:212)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated.doubleCheck(WebDoubleCheckDuplicated.scala:108)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated$.delayedEndpoint$org$bireme$dcdup$WebDoubleCheckDuplicated$1(WebDoubleCheckDuplicated.scala:67)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated$delayedInit$body.apply(WebDoubleCheckDuplicated.scala:46)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at scala.App.main(App.scala:76)
[error]         at scala.App.main$(App.scala:74)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated$.main(WebDoubleCheckDuplicated.scala:46)
[error]         at org.bireme.dcdup.WebDoubleCheckDuplicated.main(WebDoubleCheckDuplicated.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.Run.invokeMain(Run.scala:93)
[error]         at sbt.Run.run0(Run.scala:87)
[error]         at sbt.Run.execute$1(Run.scala:65)
[error]         at sbt.Run.$anonfun$run$3(Run.scala:69)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.util.Try$.apply(Try.scala:209)
[error]         at sbt.Run.directExecute$1(Run.scala:69)
[error]         at sbt.Run.run(Run.scala:78)
[error]         at sbt.Defaults$.$anonfun$bgRunMainTask$6(Defaults.scala:1146)
[error]         at sbt.Defaults$.$anonfun$bgRunMainTask$6$adapted(Defaults.scala:1141)
[error]         at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.util.Try$.apply(Try.scala:209)
[error]         at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:745)
[error] (Compile / runMain) java.io.IOException: ERROR:
[error] Total time: 2568 s, completed Apr 24, 2018 5:34:21 PM
/bases/fiadmin2/DeDup/scripts

**Comment by heitorbarbieri** [comment]
Corrigido.
