### ISSUE TITLE
Problema no check do MNTam

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/DCDup#22]
Mensagem de Erro

Executa o dedup do MNTam
[TIME-STAMP] 2018.09.28 08:15:30 [:INI:] Processa ./dedup_check.sh coleciona-sus MNTam iso-8859-1 http://dedup.bireme.org/services

- Verificacoes iniciais
Gera Arquivo para checagem de Duplicacao!
Diretorio de processamento /home/javaapps/sbt-projects/DCDup/sh
Diretorio de trabalho e arquivo /bases/fiadmin2/DeDup/wrk/coleciona-sus/in_coleciona-sus.txt
Formato utilizado
pft=if v5.1='S' then s1:=(if p(v10) then (|//@//|+v10^*) else (|//@//|+v11^*) fi), s3:=(v30^*),(if p(v12) then 'LILACS_Sas|',v2[1],'|',replace(v12^*,'|',''),'|',s3,'|',v65[1].4,'|',v31[1],'|',v32[1]'|',s1,'|',if v14[1]^*>'' then v14[1]^* fi,/ fi),(if p(v13) then 'LILACS_Sas|',v2[1],'|',replace(v13^*,'|',''),'|',s3,'|',v65[1].4,'|',v31[1],'|',v32[1]'|',s1,'|',if v14[1]^*>'' then v14[1]^* fi,/ fi),fi
Gera o txt de entrada para o check de duplicado
/home/javaapps/sbt-projects/DCDup/sh/geraPipeFile/GeraPipedFile_MNTam.sh /bases/fiadmin2/DeDup/wrk/coleciona-sus/lil_OK /bases/fiadmin2/DeDup/wrk/coleciona-sus/in_coleciona-sus_MNTam.txt
Comando para check de DeDup MNTam
/home/javaapps/sbt-projects/DCDup/sh/DoubleCheckDuplicated.sh /bases/fiadmin2/DeDup/wrk/coleciona-sus/in_coleciona-sus_MNTam.txt iso-8859-1 http://dedup.bireme.org/services lilacs_MNTam LILACS_MNTam_Five /bases/fiadmin2/DeDup/wrk/coleciona-sus/out1_coleciona-sus_MNTam.txt /bases/fiadmin2/DeDup/wrk/coleciona-sus/out2_coleciona-sus_MNTam.txt /bases/fiadmin2/DeDup/wrk/coleciona-sus/out_ok_coleciona-sus_MNTam.txt iso-8859-1
[info] Loading settings from assembly.sbt ...
[info] Loading project definition from /home/javaapps/sbt-projects/DCDup/project
[info] Loading settings from build.sbt ...
[info] Set current project to DCDup (in build file:/home/javaapps/sbt-projects/DCDup/)
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Running org.bireme.dcdup.WebDoubleCheckDuplicated /bases/fiadmin2/DeDup/wrk/coleciona-sus/in_coleciona-sus_MNTam.txt iso-8859-1 http://dedup.bireme.org/services lilacs_MNTam LILACS_MNTam_Five /bases/fiadmin2/DeDup/wrk/coleciona-sus/out1_coleciona-sus_MNTam.txt /bases/fiadmin2/DeDup/wrk/coleciona-sus/out2_coleciona-sus_MNTam.txt /bases/fiadmin2/DeDup/wrk/coleciona-sus/out_ok_coleciona-sus_MNTam.txt iso-8859-1
[error] java.io.IOException: invalid 'match' attribute value: OPTIONAL
[error] 	at br.bireme.ngrams.ParameterParser.parseNGramFields(ParameterParser.java:200)
[error] 	at br.bireme.ngrams.ParameterParser.parseParameters(ParameterParser.java:90)
[error] 	at br.bireme.ngrams.NGSchema.<init>(NGSchema.java:86)
[error] 	at org.bireme.dcdup.WebDoubleCheckDuplicated.doubleCheck(WebDoubleCheckDuplicated.scala:89)
[error] 	at org.bireme.dcdup.WebDoubleCheckDuplicated$.delayedEndpoint$org$bireme$dcdup$WebDoubleCheckDuplicated$1(WebDoubleCheckDuplicated.scala:67)
[error] 	at org.bireme.dcdup.WebDoubleCheckDuplicated$delayedInit$body.apply(WebDoubleCheckDuplicated.scala:46)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.App.main(App.scala:76)
[error] 	at scala.App.main$(App.scala:74)
[error] 	at org.bireme.dcdup.WebDoubleCheckDuplicated$.main(WebDoubleCheckDuplicated.scala:46)
[error] 	at org.bireme.dcdup.WebDoubleCheckDuplicated.main(WebDoubleCheckDuplicated.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by heitorbarbieri** [comment]
Não reproduzível na última versão
