### ISSUE TITLE
Check de Duplicado do Fonte Sas

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/DCDup#34]
Foi criado o arquivo de configuração configLILACS_Sas_Source1.cfg para o check de duplicado dos registros Fonte Sas
1 - criar o índice para o TÍTULO DA REVISTA <idxNGramField pos="3" name="titulo_revista"/> ;
2 - incluir lo no Tomcat da Produção.
3 - Informar o desenvolvedor no FI-ADMIN para implementar o check no sistema.

**Comment by heitorbarbieri** [comment]
commit 7b0563a
