### ISSUE TITLE
Comparar resultados de comparação de resultados duplicados entre o DeDup e o sistema Elsevier

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/DCDup#40]

**Comment by botturam** [comment]
seguirei o processo de exclusão dos duplicados em COVIDWHO, considerando o procesamento da Elsevier (Potential_WHO_Duplicates.csv) e o algorítimo do Renato.

**Comment by heitorbarbieri** [comment]
Arquivo com o resultado da deduplicação enviado ao Renato para que realizasse comparação.
